### ISSUE TITLE
[request] Zooming

### ISSUE THREAD

**Issue by Wurby** [kelyvin/Google-Allo-For-Desktop#14]
Love this tool so far, but the one thing that I'd love to see is a way to zoom the chat. I would love to be able to make it tiny. :)

**Comment by kelyvin** [comment]
Since this app is simply an electron wrapper around Google's web app experience (https://allo.google.com/web), if you'd like to zoom in or zoom out, you would provide the same keyboard shortcuts and commands as you would for your browser. 

So if you want to do it in the app, you can do the following:

For Mac: 
- Zoom in: [`ctrl` + `+`] (Windows & Linux) or  [`cmd` + `+`] (Mac)
- Zoom out: [`ctrl` +  `-` ]

For Windows or Linux
- Zoom in: [`cmd` + `+`]
- Zoom out: [`cmd` +  `-` ]

or simply click on the toolbar, click `View` -> `Zoom In` or `Zoom Out`

Hope this helps!
