### ISSUE TITLE
Request for "minified" functionality on Windows

### ISSUE THREAD

**Issue by ryvanvel** [kelyvin/Google-Allo-For-Desktop#4]
First up - keep up the good work.

My request is to modify the app to share similar functionality of other chat apps of it's kind - that is to say that "Closing" the app just runs it in the background. Similar to how Slack, Linechat, Wechat, Messenger all work.

**Comment by apersonnamedmike** [comment]
I would like this as well!

**Comment by kelyvin** [comment]
Thanks for creating the tray icon! I will look into this soon and get back to you. Stay tuned...

**Comment by skyborgff** [comment]
Make it flash between this tray icon and a colored one when we receive a message

**Comment by apersonnamedmike** [comment]
I think the colored icon would be great, if it could track the number of messages that are unread (kinda like how the favicon does it within a chrome tab)

also, I found this for how to do it: https://github.com/hokein/electron-sample-apps/blob/master/tray/main.js

and this is the feature request for it to happen in nativefier itself:
https://github.com/jiahaog/nativefier/issues/304

Let me know if that helps. I'd see if I could implement it myself, but I've suddenly become extremely busy. If I get some time and its still not implemented, I'll try it out and see if I can get a pull request made up.

**Comment by omouren** [comment]
Incoming
jiahaog/nativefier#457

**Comment by kelyvin** [comment]
Thanks to the great work by @omouren, tray icon support has now been implemented as part of the following pull request: https://github.com/kelyvin/Google-Allo-For-Desktop/pull/6

It currently does not do any more than the original feature request (i.e. closing the app runs it in the background), so it won't change colors or show a badge on the number of notifications unread. Because this pull request addresses the original feature request, I will close it. 

However, for any other complex features, feel free to create a proper request for it. Unfortunately, I am busy with other side ventures and that's been eating a lot of my time. So I haven't had much bandwidth to address some of the open items on my projects - hopefully someone can pick it up. :)
