### ISSUE TITLE
Profile card is cut off when the window is too narrow

### ISSUE THREAD

**Issue by blindingstars** [kelyvin/Google-Allo-For-Desktop#7]
In between the wider window mode and more mobile-like, full-width version of the profile card, the profile content gets cut off and is inaccessible until the window is resized.

![2017-11-30_22-03-15](https://user-images.githubusercontent.com/6765732/33467520-a012a5c8-d61a-11e7-8d56-a20c18718c60.gif)

Perhaps the profile card could overlay the conversation when the full width won't fit?

<sup><em>(P.S. Thank you for making this!)</em></sup>

**Comment by kelyvin** [comment]
Hi @blindingstars, thanks for submitting this issue! Unfortunately, since this shell is simply a wrapper around https://allo.google.com/, this is the default responsive design of that website. As a reuslt, there's not much I can do to fix this.

Several workarounds I can include would be to set a minimum width in order to prevent resizing the window any smaller, but that may mess up folks who prefer to keep it extremely narrow. :(

**Comment by blindingstars** [comment]
Gotcha, @kelyvin! I'll go ahead and close the issue, as that's on their end and I agree that any workarounds would cause more trouble than they are worth. Minor thing regardless. Have a great rest of the weekend!
